### PR TITLE
Sarjith/add bm extn

### PR DESCRIPTION
**Pull request by SVPToptal**

### CODE REVIEW

**Comment by luqven** [comment]
@SVPToptal could you add a description to the pull request that outlines what these changes do?

Also for the commit messages, please follow the [conventional commit guidelines](https://www.conventionalcommits.org/en/v1.0.0/).

-- 
The following commit:

`Added BM extentension cartridge for Imgix component for page designer`

Should read something like:

`feat: added bm extension cartridge for Imgix component for page designer`

If you don't know how to change the title of your commit message, follow these steps:
https://www.oreilly.com/learning-paths/learning-path-programming/9781491987360/9781491916162-video194125/

**Comment by luqven** [comment]
Oh one last thing, I recently merged some PRs into `next`. Please pull down the latest changes for `next`, checkout your branch, and rebase onto `next`, and then force push your branch so the rebase is reflected here.

**Comment by SVPToptal** [comment]
Not following the standard commit structure so decline the PR

**Comment by luqven** [comment]
> @SVPToptal could you add a description to the pull request that outlines what these changes do?
> 
> Also for the commit messages, please follow the [conventional commit guidelines](https://www.conventionalcommits.org/en/v1.0.0/).
> 
> --
> The following commit:
> 
> `Added BM extentension cartridge for Imgix component for page designer`
> 
> Should read something like:
> 
> `feat: added bm extension cartridge for Imgix component for page designer`
> 
> If you don't know how to change the title of your commit message, follow these steps:
> https://www.oreilly.com/learning-paths/learning-path-programming/9781491987360/9781491916162-video194125/

@SVPToptal drawing you attention to this again in the hopes that it helps.

**Pull request closed without merging**
