### PR TITLE
PE-1579-1 Trigger imgix modal

### PR DESCRIPTION
**Pull request by syedbadshah-toptal**
### Stacked PR Chain: PE-1579-1
| PR | Title | Status |  Merges Into  |
|:--:|:------|:-------|:-------------:|
|#86|👉 PE-1579-1 Trigger imgix modal|Pending|-|
|#88|PE-1579-1 refactor: memoise handle-breakout-open|Pending|#86|
|#89|PE-1579-1 feat: show selected image in sidebar|Pending|#88|

### CODE REVIEW

**Review by luqven — CHANGES_REQUESTED** [review]
There are some conflicts here with `next` that need to be resolved before merging.

**Comment by syedbadshah-toptal** [comment]
conflicts resolved.

**Review by frederickfogerty — CHANGES_REQUESTED** [review]
I'm not sure what the purpose of this PR is, I will need a description or indication of this before I can review this

**Comment by luqven** [comment]
Closing this in favor of #93

**Pull request closed without merging**
