### PR TITLE
fix: typescript code version target was incompatible with SF backend

### PR DESCRIPTION
**Pull request by frederickfogerty**
ssia

### CODE REVIEW

**Comment by frederickfogerty** [comment]
Current dependencies on/for this PR:
* next
  * **PR #309** <a href="https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/309" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by luqven — APPROVED** [review]

**Review by luqven — COMMENTED** [review]
[gandalf-beautiful](https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/309)

**Review by luqven — APPROVED** [review]
going to merge this in to unblock other work [shipped-ish](https://app.graphite.dev/github/pr/imgix/sf-commerce-cloud/309)

**Comment by frederickfogerty** [comment]
Haha @luqven I don't think this is quite the 🚢 GIF you were hoping for 😅

**Comment by luqven** [comment]
> Haha @luqven I don't think this is quite the 🚢 GIF you were hoping for 😅 

@frederickfogerty i didn't have any other shipped gifs in hand 🤣

**Pull request merged**
