### PR TITLE
[fred] Added apikey to defaultParams

### PR DESCRIPTION
**Pull request by frederickfogerty**
I rebased extracted this commit to another PR so we could discuss it @syedbadshah-toptal.

### Stacked PR Chain: fred
| PR | Title | Status |  Merges Into  |
|:--:|:------|:-------|:-------------:|
|#79|👉 Added apikey to defaultParams|Pending|-|
|#76|~~feat: implement responsive images and set ixlib~~|**Merged**|-|
|#77|~~chore: write template logic to handle default params~~|**Merged**|#76|
|#82|~~feat: add imgix parameters to component sidebar~~|**Merged**|#77|
|#83|~~feat: correctly set imgix parameters on rendered image~~|**Merged**|#82|

### CODE REVIEW

**Comment by frederickfogerty** [comment]
@syedbadshah-toptal I was wondering if you could explain a bit about the purpose of this PR? The API key is not necessary in the default parameters. Was this more meant to be an example or something of how to pull the global default parameters?

**Comment by luqven** [comment]
@frederickfogerty this PR still need merging/approval? Unsure about the status given the conflicts and outstanding comments.

**Comment by syedbadshah-toptal** [comment]
> @syedbadshah-toptal I was wondering if you could explain a bit about the purpose of this PR? The API key is not necessary in the default parameters. Was this more meant to be an example or something of how to pull the global default parameters?

reverted api key parameter because this was already done by luis.

**Comment by frederickfogerty** [comment]
I'm going to close this since I think it's covered elsewhere

**Pull request closed without merging**
