### PR TITLE
feat: implement content script

### PR DESCRIPTION
**Pull request by frederickfogerty**
This PR implements the content script fully. It uses an interval to ensure that the target element is found reliably, and stops after 30s. Also it now replaces the whole imgix section so the React app can use the whole available space.

### CODE REVIEW

**Comment by frederickfogerty** [comment]
Current dependencies on/for this PR:
* next
  * **PR #179** 
    * **PR #181** 
      * **PR #182** 
        * **PR #180**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by luqven — APPROVED** [review]
great work, nicely done

**Comment by frederickfogerty** [comment]
@luqven made a small little change if you want to take a look 🙌

**Comment by luqven** [comment]
@frederickfogerty 30s seems like a lot.. shouldn't this take much less than that? Maybe I'm overestimating how fast the SFCC product page loads 😆

**Comment by frederickfogerty** [comment]
@luqven Yeah 30s is a long time... but I was just being conservative. To be clear it doesn't wait that long, it's only a timeout to _stop_ searching

**Comment by frederickfogerty** [comment]
@luqven feel free to merge after you've reviewed again

**Review by luqven — APPROVED** [review]
LGTM

**Pull request merged**
